### ISSUE TITLE
StaffChat

### ISSUE THREAD

**Issue by egold555** [egold555/CrotusCord#1]
/staffchat <msg>
/staffchat <enable:disable>

&8[&a&lStaffChat&8] &8[&2&lSever&8] &8» &8[&a&lStaffMember&8] &2&l

**Comment by awsomesteve55** [comment]
&8[&a&lStaff Chat&8] &8[&2&lSever&8] &8» &8[&a&lStaffMember&8] &2&l
If you can do a space
